const {

    NODE_ENV,
    PORT,
    REACT_APP_URL,
    MONGODB_CONNECTION_URL,
    PASSWORD_SECRET,
    ACCESS_SECRET,
    REFRESH_SECRET,
    COOKIE_SECRET,
    VERCEL_URL

}  = process.env

module.exports.PORT = PORT
module.exports.REACT_APP_URL = NODE_ENV === 'development' ? REACT_APP_URL : VERCEL_URL
module.exports.CLOUD_DB_URL = MONGODB_CONNECTION_URL
module.exports.PASSWORD_SECRET = PASSWORD_SECRET
module.exports.ACCESS_SECRET = ACCESS_SECRET
module.exports.REFRESH_SECRET = REFRESH_SECRET
module.exports.COOKIE_SECRET = COOKIE_SECRET